name: 🌈 Update README auto 

on:
  schedule:
    - cron: "0 13 */2 * *"

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Install
        run: yarn

      - name: Update data
        run: node ./active-script/update-readme.js

      - name: Commit and push if changed
        run: |-
          git diff
          git config --global user.email "xrkffgg@vip.qq.com"
          git config --global user.name "xrkffgg"
          git pull
          git add -A
          git commit -m "🤖 auto: updated README" || exit 0
          git push
